# Generated by Django 4.0.6 on 2022-07-13 11:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailcore', '0069_log_entry_jsonfield'),
        ('blog', '0002_blocpage'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='BlocPage',
            new_name='BlogPage',
        ),
    ]
