# Generated by Django 4.0.6 on 2022-07-20 13:03

from django.db import migrations
import wagtail.blocks
import wagtail.fields
import wagtail.images.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_blogpage_categories'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpage',
            name='body',
            field=wagtail.fields.StreamField([('paragraph', wagtail.blocks.RichTextBlock(features=['h1', 'h2', 'h3', 'bold', 'italic', 'link', 'hr'], label='Paragraphe')), ('image', wagtail.images.blocks.ImageChooserBlock()), ('two_columns', wagtail.blocks.StructBlock([('position', wagtail.blocks.ChoiceBlock(choices=[('left', '70%-30%'), ('middle', '50%-50%'), ('right', '30%-70%')], label='Disposition des colonnes')), ('left_column', wagtail.blocks.StreamBlock([('paragraph', wagtail.blocks.RichTextBlock(label='Paragraphe')), ('image', wagtail.images.blocks.ImageChooserBlock()), ('card', wagtail.blocks.StructBlock([('paragraph', wagtail.blocks.RichTextBlock(label='Paragraphe')), ('image', wagtail.images.blocks.ImageChooserBlock())]))], icon='arrow-left', label='Colonne de gauche')), ('right_column', wagtail.blocks.StreamBlock([('paragraph', wagtail.blocks.RichTextBlock(label='Paragraphe')), ('image', wagtail.images.blocks.ImageChooserBlock()), ('card', wagtail.blocks.StructBlock([('paragraph', wagtail.blocks.RichTextBlock(label='Paragraphe')), ('image', wagtail.images.blocks.ImageChooserBlock())]))], icon='arrow-right', label='Colonne de droite'))])), ('three_columns', wagtail.blocks.StructBlock([('left_column', wagtail.blocks.StreamBlock([('paragraph', wagtail.blocks.RichTextBlock(label='Paragraphe')), ('image', wagtail.images.blocks.ImageChooserBlock()), ('card', wagtail.blocks.StructBlock([('paragraph', wagtail.blocks.RichTextBlock(label='Paragraphe')), ('image', wagtail.images.blocks.ImageChooserBlock())]))], icon='arrow-left', label='Colonne de gauche')), ('middle_column', wagtail.blocks.StreamBlock([('paragraph', wagtail.blocks.RichTextBlock(label='Paragraphe')), ('image', wagtail.images.blocks.ImageChooserBlock()), ('card', wagtail.blocks.StructBlock([('paragraph', wagtail.blocks.RichTextBlock(label='Paragraphe')), ('image', wagtail.images.blocks.ImageChooserBlock())]))], label='Colonne centrale')), ('right_column', wagtail.blocks.StreamBlock([('paragraph', wagtail.blocks.RichTextBlock(label='Paragraphe')), ('image', wagtail.images.blocks.ImageChooserBlock()), ('card', wagtail.blocks.StructBlock([('paragraph', wagtail.blocks.RichTextBlock(label='Paragraphe')), ('image', wagtail.images.blocks.ImageChooserBlock())]))], icon='arrow-right', label='Colonne de droite'))])), ('card', wagtail.blocks.StructBlock([('paragraph', wagtail.blocks.RichTextBlock(label='Paragraphe')), ('image', wagtail.images.blocks.ImageChooserBlock())]))], null=True, use_json_field=None, verbose_name='Contenu'),
        ),
    ]
