# Generated by Django 4.0.6 on 2022-07-19 12:30

from django.db import migrations, models
import django.db.models.deletion
import wagtail.blocks
import wagtail.fields
import wagtail.images.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailcore', '0069_log_entry_jsonfield'),
        ('home', '0007_alter_homepage_banner_background_image_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClassicPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('body', wagtail.fields.StreamField([('paragraph', wagtail.blocks.RichTextBlock(features=['h1', 'h2', 'h3', 'bold', 'italic', 'link', 'hr'], label='Paragraphe')), ('image', wagtail.images.blocks.ImageChooserBlock()), ('two_columns', wagtail.blocks.StructBlock([('position', wagtail.blocks.ChoiceBlock(choices=[('left', '70%-30%'), ('middle', '50%-50%'), ('right', '30%-70%')], label='Disposition des colonnes')), ('left_column', wagtail.blocks.StreamBlock([('paragraph', wagtail.blocks.RichTextBlock(label='Paragraphe')), ('image', wagtail.images.blocks.ImageChooserBlock())], icon='arrow-left', label='Colonne de gauche')), ('right_column', wagtail.blocks.StreamBlock([('paragraph', wagtail.blocks.RichTextBlock(label='Paragraphe')), ('image', wagtail.images.blocks.ImageChooserBlock())], icon='arrow-right', label='Colonne de droite'))])), ('three_columns', wagtail.blocks.StructBlock([('left_column', wagtail.blocks.StreamBlock([('paragraph', wagtail.blocks.RichTextBlock(label='Paragraphe')), ('image', wagtail.images.blocks.ImageChooserBlock())], icon='arrow-left', label='Colonne de gauche')), ('middle_column', wagtail.blocks.StreamBlock([('paragraph', wagtail.blocks.RichTextBlock(label='Paragraphe')), ('image', wagtail.images.blocks.ImageChooserBlock())], label='Colonne centrale')), ('right_column', wagtail.blocks.StreamBlock([('paragraph', wagtail.blocks.RichTextBlock(label='Paragraphe')), ('image', wagtail.images.blocks.ImageChooserBlock())], icon='arrow-right', label='Colonne de droite'))]))], use_json_field=None, verbose_name='Contenu')),
            ],
            options={
                'verbose_name': 'Page classique',
            },
            bases=('wagtailcore.page',),
        ),
    ]
