# Generated by Django 4.0.6 on 2022-07-22 08:01

from django.db import migrations
import wagtail.blocks
import wagtail.fields
import wagtail.images.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0014_alter_classicpage_body_alter_homepage_body'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homepage',
            name='body',
            field=wagtail.fields.StreamField([('paragraph', wagtail.blocks.RichTextBlock(features=['h1', 'h2', 'h3', 'bold', 'italic', 'link', 'hr'], label='Paragraphe')), ('image', wagtail.images.blocks.ImageChooserBlock()), ('two_columns', wagtail.blocks.StructBlock([('position', wagtail.blocks.ChoiceBlock(choices=[('left', '70%-30%'), ('middle', '50%-50%'), ('right', '30%-70%')], label='Disposition des colonnes')), ('left_column', wagtail.blocks.StreamBlock([('paragraph', wagtail.blocks.RichTextBlock(label='Paragraphe')), ('image', wagtail.images.blocks.ImageChooserBlock())], icon='arrow-left', label='Colonne de gauche')), ('right_column', wagtail.blocks.StreamBlock([('paragraph', wagtail.blocks.RichTextBlock(label='Paragraphe')), ('image', wagtail.images.blocks.ImageChooserBlock())], icon='arrow-right', label='Colonne de droite'))])), ('three_columns', wagtail.blocks.StructBlock([('left_column', wagtail.blocks.StreamBlock([('paragraph', wagtail.blocks.RichTextBlock(label='Paragraphe')), ('image', wagtail.images.blocks.ImageChooserBlock())], icon='arrow-left', label='Colonne de gauche')), ('middle_column', wagtail.blocks.StreamBlock([('paragraph', wagtail.blocks.RichTextBlock(label='Paragraphe')), ('image', wagtail.images.blocks.ImageChooserBlock())], label='Colonne centrale')), ('right_column', wagtail.blocks.StreamBlock([('paragraph', wagtail.blocks.RichTextBlock(label='Paragraphe')), ('image', wagtail.images.blocks.ImageChooserBlock())], icon='arrow-right', label='Colonne de droite'))])), ('cards', wagtail.blocks.StructBlock([('cards', wagtail.blocks.ListBlock(wagtail.blocks.StructBlock([('title', wagtail.blocks.CharBlock(help_text='Bold title text for this card. Max length of 100 characters.', max_length=100)), ('text', wagtail.blocks.TextBlock(help_text='Optional text for this card. Max length is 255 characters', max_length=255, required=False)), ('image', wagtail.images.blocks.ImageChooserBlock(help_text='Images will be automatically cropped 570px by 370px')), ('link', wagtail.blocks.StructBlock([('link_text', wagtail.blocks.CharBlock(default='More details', max_length=50)), ('internal_page', wagtail.blocks.PageChooserBlock(required=False)), ('external_link', wagtail.blocks.URLBlock(required=False))], help_text='Enter a link or select a page'))])))])), ('large_image', wagtail.images.blocks.ImageChooserBlock(help_text='Cette image va être rognée de 1400px par 300px', template='blocks/large_image_block.html')), ('small_image', wagtail.images.blocks.ImageChooserBlock(help_text='Cette image va être rognée de 1400px par 300px', template='blocks/small_image_block.html'))], null=True, use_json_field=None, verbose_name='Contenu'),
        ),
    ]
