# Generated by Django 4.0.6 on 2022-07-26 08:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailimages', '0024_index_image_file_hash'),
        ('home', '0018_alter_classicpage_body'),
    ]

    operations = [
        migrations.AddField(
            model_name='classicpage',
            name='banner_background_image',
            field=models.ForeignKey(help_text='Image de la banière', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image'),
        ),
    ]
