# Generated by Django 4.0.6 on 2022-07-26 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='menuitem',
            name='icon',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
