# Generated by Django 4.0.6 on 2022-07-26 09:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0002_menuitem_icon'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='menuitem',
            name='icon',
        ),
    ]
